#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER "$IDENTITY_USER" with encrypted password '$IDENTITY_PASSWORD';
	CREATE DATABASE "$IDENTITY_DB";
	GRANT ALL PRIVILEGES ON DATABASE "$IDENTITY_DB" TO "$IDENTITY_USER";
EOSQL